-- Seed: players
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (1, 'Mike Thorn');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (2, 'Dave Steel');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (3, 'Chris Arrow');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (4, 'Marco Berger');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (5, 'Felix Gross');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (6, 'John Bull');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (7, 'Max Richter');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (8, 'Pete Hammer');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (9, 'Lukas Weber');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (10, 'Simon Adler');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (11, 'Luke Swift');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (12, 'Tom Knight');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (13, 'Erik Frost');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (14, 'Ben Schwarz');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (15, 'Jonas Wolf');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (16, 'David Maurer');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (17, 'Paul Graf');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (18, 'Leo Fischer');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (19, 'Nils Hoffmann');
INSERT INTO public.players (id, name) OVERRIDING SYSTEM VALUE VALUES (20, 'Tim Krüger');

-- Note: slug is auto-generated by the DB (GENERATED ALWAYS AS lower(replace(name, ' ', '-')))